---HOMEWORK1---
CREATE SEQUENCE EMPLOYEE
 START WITH 230;

INSERT
  INTO
  	   EMPLOYEE
       (
       EMP_ID
     , EMP_NAME
     , EMP_NO
     , EMAIL
     , PHONE
     , DEPT_CODE
     , JOB_CODE
     , SAL_LEVEL
     , SALARY
     , BONUS
     , HIRE_DATE  
       )
VALUES
 	   (
	   SEQ_EID.NEXTVAL
	 , '홍길길'
	 , '631010-2653546'
	 , 'kth04@kh.or.kr'
	 , '01077607879'
	 , 'D9'
	 , 'J5'
	 , 'S4'
	 , 5000000
	 , 100
	 , SYSDATE
 	   );
COMMIT;
--DROP TABLE EMPLOYEE;
SELECT * FROM EMPLOYEE;
-------------------------------------------------------------
---HOMEWORK2---
CREATE SEQUENCE SEQ_PLANT
 START WITH 1;

CREATE TABLE TB_PLANT(
	PLANT_ID NUMBER PRIMARY KEY,
    PLANT_NAME NVARCHAR2(30) NOT NULL,
    PLANT_TYPE NVARCHAR2(30) NOT NULL
);

INSERT
  INTO
       TB_PLANT
VALUES
       (
       SEQ_PLANT.NEXTVAL
     , '몬스테라'
     , '열대관엽식물'
       );
COMMIT;
SELECT * FROM TB_PLANT;
----------------------------------------------------
SELECT
       PLANT_ID
     , PLANT_NAME
     , PLANT_TYPE
 FROM
      TB_PLANT
ORDER
   BY 
      PLANT_ID;

----------------------------------------------------
---HOMEWORK3---
DROP TABLE TB_EVENT;
CREATE TABLE TB_EVENT(
	EVENT_NO NUMBER PRIMARY KEY,
	EVENT_ID VARCHAR2(15) UNIQUE NOT NULL,
	TITLE VARCHAR2(255) NOT NULL,
	DESCRIPTION CLOB,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	REWARD_POINT NUMBER NOT NULL
);
DROP SEQUENCE SEQ_EVENT;
CREATE SEQUENCE SEQ_EVENT START WITH 1;

INSERT
  INTO
       TB_EVENT
VALUES
       (
       SEQ_EVENT.NEXTVAL
     , 'A01'
     , '아침 6시 기상하고 인증하기!'
     , '매일 아침에 함꼐 일찍 기상하고 더 의미있는 하루를 시작을 같이 만들어가요!'
     , TO_DATE('2025-09-01','YYYY-MM-DD')
     , TO_DATE('2025-09-07','YYYY-MM-DD')
     , 500
       );

COMMIT;

SELECT * FROM TB_EVENT;
----------------------
SELECT
	   EVENT_NO
     , EVENT_ID
     , TITLE
     , DESCRIPTION
     , START_DATE
     , END_DATE
     , REWARD_POINT
  FROM
       TB_EVENT
 ORDER
    BY
       START_DATE;
SELECT * FROM TB_EVENT;
---------------------------
-- 1) 챌린지 사용자 테이블 --
DROP TABLE CH_USER CASCADE CONSTRAINTS;

CREATE TABLE CH_USER(
	USER_NO NUMBER PRIMARY KEY,					-- PK, 시퀀스로 관리
	USER_ID VARCHAR2(30) UNIQUE NOT NULL,		-- 로그인 ID
	USER_NAME VARCHAR2(50) NOT NULL,			-- 이름
	EMAIL VARCHAR2(100) UNIQUE,					-- 이메일(중복 방지)
	PASSWORD VARCHAR2(100) NOT NULL,			-- 비밀번호 
	ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL	-- 가입일
);
-- USER PK 시퀀스
DROP SEQUENCE SEQ_USER;

CREATE SEQUENCE SEQ_USER START WITH 1 NOCACHE;

--2) 챌린지 테이블 --
-- CHALLENGE 테이블 삭제
DROP TABLE TB_CHALLENGE CASCADE CONSTRAINTS;

CREATE TABLE TB_CHALLENGE(
	CHALLENGE_NO NUMBER PRIMARY KEY,			-- PK, 시퀀스
	CHALLENGE_ID VARCHAR2(30) UNIQUE NOT NULL,	-- 외부 공개 ID
	TITLE VARCHAR2(255) NOT NULL,				-- 제목	
	DESCRIPTION CLOB, 							-- 설명
	START_DATE DATE NOT NULL,					-- 시작일
	END_DATE DATE NOT NULL,						-- 종료일
	REWARD_POINT NUMBER DEFAULT 0 NOT NULL,		-- 포인트(기본 0)
	CREATOR_USER_NO NUMBER NOT NULL,			-- 생성자 FK (TB_USER.USER_NO)
	ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,	-- 생성일시
	CONSTRAINT CK_CHALLENGE_DATE CHECK (START_DATE <= END_DATE),
	CONSTRAINT FK_CHALLENGE_CREATOR FOREIGN KEY (CREATOR_USER_NO)
		REFERENCES CH_USER(USER_NO)
);

-- 챌린지 PK 시퀀스
DROP SEQUENCE SEQ_CHALLENGE;
CREATE SEQUENCE SEQ_CHALLENGE START WITH 1 NOCACHE;

---------
-- 1) 챌린지 유저 생성
INSERT 
  INTO 
       CH_USER 
       (
       USER_NO
     , USER_ID
     , USER_NAME
     , EMAIL
     , PASSWORD
	   ) 
VALUES 
       (
	    SEQ_USER.NEXTVAL
	  , 'psh08'
	  , '박수현'
	  , 'psh08@kh.co.kr'
	  , '1234'
	    );
COMMIT;
INSERT 
  INTO 
       CH_USER 
       (
       USER_NO
     , USER_ID
     , USER_NAME
     , EMAIL
     , PASSWORD
	   ) 
VALUES 
	   (
       SEQ_USER.NEXTVAL
     , 'psh09'
     , '홍길동'
     , 'psh09@kh.co.kr'
     ,  '1234'
      );
SELECT * FROM CH_USER;
COMMIT;
SELECT USER_NO, USER_ID, USER_NAME, EMAIL, ENROLL_DATE FROM CH_USER ORDER BY USER_NO DESC;
-- 2) 챌린지 생성 (CREATOR_USER_NO = 1 가정)
INSERT 
  INTO 
       TB_CHALLENGE 
       (
       CHALLENGE_NO
     , CHALLENGE_ID
     , TITLE
     , DESCRIPTION
     , START_DATE
     , END_DATE
     , REWARD_POINT
     , CREATOR_USER_NO
     , ENROLL_DATE
	   ) 
VALUES 
		(
	    SEQ_CHALLENGE.NEXTVAL
	  , 'CHL-A'
	  , '아침 6시 기상 챌린지'
	  , '매일 아침 6시에 기상 후 인증샷 업로드'
	  , DATE '2025-09-05'
	  , DATE '2025-09-30'
	  , 100
	  ,  1
	  , SYSDATE
		);
COMMIT;
INSERT 
  INTO 
       TB_CHALLENGE 
       (
       CHALLENGE_NO
     , CHALLENGE_ID
     , TITLE
     , DESCRIPTION
     , START_DATE
     , END_DATE
     , REWARD_POINT
     , CREATOR_USER_NO
     , ENROLL_DATE
	   ) 
VALUES 
	   (
	   SEQ_CHALLENGE.NEXTVAL
	 , 'CHL-B'
	 , 'SNS 인증하기!'
	 , '매일 3번 인증샷 업로드'
	 , DATE '2025-09-30'
	 , DATE '2025-10-31'
	 , 200
	 , 2
	 , SYSDATE
	   );
COMMIT;
SELECT CHALLENGE_NO, CHALLENGE_ID, TITLE, DESCRIPTION, START_DATE, END_DATE, REWARD_POINT, CREATOR_USER_NO, ENROLL_DATE FROM TB_CHALLENGE ORDER BY CHALLENGE_NO DESC;

-----------------------------------------------------------
-- 3) 챌린지 참여 관계 테이블 (유저 <-> 챌린지)
------------------------------------------------------------
SELECT u.USER_NO, u.USER_ID, c. CREATOR_USER_NO, c.CHALLENGE_ID, c.TITLE
FROM CH_USER u
INNER JOIN TB_CHALLENGE c
        ON c.CREATOR_USER_NO = u.USER_NO
ORDER BY u.USER_NO, c. CREATOR_USER_NO;























