DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR2(15) UNIQUE NOT NULL, -- 중복방지
    USERPWD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(30),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL -- 시퀀스로 만들 예정
);

DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;

INSERT INTO MEMBER
VALUES (SEQ_USERNO.NEXTVAL, 'admin', '1234', '관리자', 'admin@kh.com', '2025/08/16');

INSERT INTO MEMBER
VALUES (SEQ_USERNO.NEXTVAL, 'user01', 'pass01', '홍길동', 'hong@naver.com', SYSDATE);

COMMIT;

CREATE SEQUENCE SEQ_BNO;
SELECT * FROM MEMBER;

DROP TABLE BOARD;
CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE NVARCHAR2(300) NOT NULL, -- 사용자에게 받아서 작업
    BOARD_CONTENT NVARCHAR2(1000) NOT NULL, -- 사용자에게 받아서 작업
    BOARD_WRITER NUMBER REFERENCES MEMBER(USERNO), -- 외래키 -- 사용자에게 받아서 작업
    CREATE_DATE DATE DEFAULT SYSDATE,
    DELETE_YN CHAR(1) DEFAULT 'N'	-- 삭제 여부 컬럼
);

SELECT * FROM BOARD;

SELECT * FROM MEMBER;

--INSERT INTO BOARD VALUES(1, '제목', '내용', 1, SYSDATE, 'N');
--SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, USERID, CREATE_DATE
--  FROM BOARD
--  JOIN MEMBER ON (BOARD_WRITER = USERNO);
-- WHERE DELETE_YN = 'N'; --> 이럴 경우 INSERT는 맞지만 SELECT 할 경우 안됨
------------------------------------------------------
