CREATE TABLE KH_MEMBER(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(30) UNIQUE NOT NULL,
	USER_PWD VARCHAR2(30) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE, -- 가입시간
	MODIFY_DATE DATE DEFAULT SYSDATE, -- 수정한 시간
	STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N'))
);

CREATE SEQUENCE KH_UNO NOCACHE;
-- default 메뉴가 많을 경우 아래와 같이() 가는 걸 선호한다. / 여기의 connection session과 mybatis session이랑 다르기 때문에 commit 해야 사용할 수 있다.
INSERT INTO KH_MEMBER(USER_NO, USER_ID, USER_PWD, USER_NAME, EMAIL) VALUES (KH_UNO.NEXTVAL, 'admin', '1234', '홍길동', 'hong@kh.CLASS_ROOM ');
COMMIT;

SELECT * FROM KH_MEMBER;



