CREATE TABLE TB_STUDENT(
	STUDENT_ID NUMBER PRIMARY KEY,
	STUDENT_NAME NVARCHAR2(5) NOT NULL,
	ENROLL_DATE DATE NOT NULL
);

INSERT
  INTO
       TB_STUDENT
VALUES
       (
       1
     , '홍길동'
     , SYSDATE
       );
COMMIT;
SELECT * FROM TB_STUDENT;
