
CREATE TABLE TB_MAJOR (
    MAJOR_ID NUMBER PRIMARY KEY,
    MAJOR_NAME NVARCHAR2(30) NOT NULL,
    DEPARTMENT_NAME NVARCHAR2(30) NOT NULL,
    CREDIT_HOURS NUMBER NOT NULL
);

CREATE TABLE TB_DORMITORY (
    DORM_ID NUMBER PRIMARY KEY,
    DORM_NAME NVARCHAR2(30) NOT NULL,
    DORM_LOCATION NVARCHAR2(30) NOT NULL,
    DORM_LEADER NVARCHAR2(30) NOT NULL
);

CREATE TABLE TB_STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    STUDENT_NAME NVARCHAR2(20) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')) NOT NULL,
    ENROLL_DATE DATE NOT NULL,
    MAJOR_ID NUMBER,
    DORM_ID NUMBER,
    CONSTRAINT FK_TB_STUDENTS_MAJAR FOREIGN KEY (MAJOR_ID) REFERENCES TB_MAJOR(MAJOR_ID),
    CONSTRAINT FK_TB_STUDENTS_DORM FOREIGN KEY (DORM_ID) REFERENCES TB_DORMITORY(DORM_ID)
);

SELECT * FROM TB_MAJOR;
SELECT * FROM TB_DORMITORY;
SELECT * FROM TB_STUDENT;